// Generated by gencpp from file beginner_tutorials/ask_BMI.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ASK_BMI_H
#define BEGINNER_TUTORIALS_MESSAGE_ASK_BMI_H

#include <ros/service_traits.h>


#include <beginner_tutorials/ask_BMIRequest.h>
#include <beginner_tutorials/ask_BMIResponse.h>


namespace beginner_tutorials
{

struct ask_BMI
{

typedef ask_BMIRequest Request;
typedef ask_BMIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ask_BMI
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::ask_BMI > {
  static const char* value()
  {
    return "3de0e12df6c14255537cca18d991ce8d";
  }

  static const char* value(const ::beginner_tutorials::ask_BMI&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::ask_BMI > {
  static const char* value()
  {
    return "beginner_tutorials/ask_BMI";
  }

  static const char* value(const ::beginner_tutorials::ask_BMI&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::ask_BMIRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::ask_BMI >
template<>
struct MD5Sum< ::beginner_tutorials::ask_BMIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::ask_BMI >::value();
  }
  static const char* value(const ::beginner_tutorials::ask_BMIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::ask_BMIRequest> should match
// service_traits::DataType< ::beginner_tutorials::ask_BMI >
template<>
struct DataType< ::beginner_tutorials::ask_BMIRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::ask_BMI >::value();
  }
  static const char* value(const ::beginner_tutorials::ask_BMIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::ask_BMIResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::ask_BMI >
template<>
struct MD5Sum< ::beginner_tutorials::ask_BMIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::ask_BMI >::value();
  }
  static const char* value(const ::beginner_tutorials::ask_BMIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::ask_BMIResponse> should match
// service_traits::DataType< ::beginner_tutorials::ask_BMI >
template<>
struct DataType< ::beginner_tutorials::ask_BMIResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::ask_BMI >::value();
  }
  static const char* value(const ::beginner_tutorials::ask_BMIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ASK_BMI_H
