// Generated by gencpp from file beginner_tutorials/ask_BMIRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ASK_BMIREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_ASK_BMIREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ask_BMIRequest_
{
  typedef ask_BMIRequest_<ContainerAllocator> Type;

  ask_BMIRequest_()
    : height(0.0)
    , weight(0.0)  {
    }
  ask_BMIRequest_(const ContainerAllocator& _alloc)
    : height(0.0)
    , weight(0.0)  {
  (void)_alloc;
    }



   typedef float _height_type;
  _height_type height;

   typedef float _weight_type;
  _weight_type weight;





  typedef boost::shared_ptr< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ask_BMIRequest_

typedef ::beginner_tutorials::ask_BMIRequest_<std::allocator<void> > ask_BMIRequest;

typedef boost::shared_ptr< ::beginner_tutorials::ask_BMIRequest > ask_BMIRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::ask_BMIRequest const> ask_BMIRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator2> & rhs)
{
  return lhs.height == rhs.height &&
    lhs.weight == rhs.weight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c714d1effcb9d7045df53d374d18e3d7";
  }

  static const char* value(const ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc714d1effcb9d704ULL;
  static const uint64_t static_value2 = 0x5df53d374d18e3d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ask_BMIRequest";
  }

  static const char* value(const ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 height\n"
"float32 weight\n"
;
  }

  static const char* value(const ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ask_BMIRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ask_BMIRequest_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "weight: ";
    Printer<float>::stream(s, indent + "  ", v.weight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ASK_BMIREQUEST_H
