// Generated by gencpp from file beginner_tutorials/ask_BMIResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ASK_BMIRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_ASK_BMIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ask_BMIResponse_
{
  typedef ask_BMIResponse_<ContainerAllocator> Type;

  ask_BMIResponse_()
    : BMI(0.0)  {
    }
  ask_BMIResponse_(const ContainerAllocator& _alloc)
    : BMI(0.0)  {
  (void)_alloc;
    }



   typedef float _BMI_type;
  _BMI_type BMI;





  typedef boost::shared_ptr< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ask_BMIResponse_

typedef ::beginner_tutorials::ask_BMIResponse_<std::allocator<void> > ask_BMIResponse;

typedef boost::shared_ptr< ::beginner_tutorials::ask_BMIResponse > ask_BMIResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::ask_BMIResponse const> ask_BMIResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator2> & rhs)
{
  return lhs.BMI == rhs.BMI;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d24e9092ad345fe90a3db3d59e270dc5";
  }

  static const char* value(const ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd24e9092ad345fe9ULL;
  static const uint64_t static_value2 = 0x0a3db3d59e270dc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ask_BMIResponse";
  }

  static const char* value(const ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 BMI\n"
"\n"
;
  }

  static const char* value(const ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BMI);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ask_BMIResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ask_BMIResponse_<ContainerAllocator>& v)
  {
    s << indent << "BMI: ";
    Printer<float>::stream(s, indent + "  ", v.BMI);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ASK_BMIRESPONSE_H
