// Generated by gencpp from file tm_msgs/Ask_img_AD.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ASK_IMG_AD_H
#define TM_MSGS_MESSAGE_ASK_IMG_AD_H

#include <ros/service_traits.h>


#include <tm_msgs/Ask_img_ADRequest.h>
#include <tm_msgs/Ask_img_ADResponse.h>


namespace tm_msgs
{

struct Ask_img_AD
{

typedef Ask_img_ADRequest Request;
typedef Ask_img_ADResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Ask_img_AD
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::Ask_img_AD > {
  static const char* value()
  {
    return "718c3a88dd0f5e8414a94bc17ba46265";
  }

  static const char* value(const ::tm_msgs::Ask_img_AD&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::Ask_img_AD > {
  static const char* value()
  {
    return "tm_msgs/Ask_img_AD";
  }

  static const char* value(const ::tm_msgs::Ask_img_AD&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::Ask_img_ADRequest> should match
// service_traits::MD5Sum< ::tm_msgs::Ask_img_AD >
template<>
struct MD5Sum< ::tm_msgs::Ask_img_ADRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::Ask_img_AD >::value();
  }
  static const char* value(const ::tm_msgs::Ask_img_ADRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::Ask_img_ADRequest> should match
// service_traits::DataType< ::tm_msgs::Ask_img_AD >
template<>
struct DataType< ::tm_msgs::Ask_img_ADRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::Ask_img_AD >::value();
  }
  static const char* value(const ::tm_msgs::Ask_img_ADRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::Ask_img_ADResponse> should match
// service_traits::MD5Sum< ::tm_msgs::Ask_img_AD >
template<>
struct MD5Sum< ::tm_msgs::Ask_img_ADResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::Ask_img_AD >::value();
  }
  static const char* value(const ::tm_msgs::Ask_img_ADResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::Ask_img_ADResponse> should match
// service_traits::DataType< ::tm_msgs::Ask_img_AD >
template<>
struct DataType< ::tm_msgs::Ask_img_ADResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::Ask_img_AD >::value();
  }
  static const char* value(const ::tm_msgs::Ask_img_ADResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_ASK_IMG_AD_H
