// Generated by gencpp from file tm_msgs/Ask_imgResponse.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ASK_IMGRESPONSE_H
#define TM_MSGS_MESSAGE_ASK_IMGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tm_msgs
{
template <class ContainerAllocator>
struct Ask_imgResponse_
{
  typedef Ask_imgResponse_<ContainerAllocator> Type;

  Ask_imgResponse_()
    : ok(false)
    , error()  {
    }
  Ask_imgResponse_(const ContainerAllocator& _alloc)
    : ok(false)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Ask_imgResponse_

typedef ::tm_msgs::Ask_imgResponse_<std::allocator<void> > Ask_imgResponse;

typedef boost::shared_ptr< ::tm_msgs::Ask_imgResponse > Ask_imgResponsePtr;
typedef boost::shared_ptr< ::tm_msgs::Ask_imgResponse const> Ask_imgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_msgs::Ask_imgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tm_msgs::Ask_imgResponse_<ContainerAllocator1> & lhs, const ::tm_msgs::Ask_imgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tm_msgs::Ask_imgResponse_<ContainerAllocator1> & lhs, const ::tm_msgs::Ask_imgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14d6fca830116fb9833d983a296f00ed";
  }

  static const char* value(const ::tm_msgs::Ask_imgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14d6fca830116fb9ULL;
  static const uint64_t static_value2 = 0x833d983a296f00edULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_msgs/Ask_imgResponse";
  }

  static const char* value(const ::tm_msgs::Ask_imgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"string error\n"
"\n"
;
  }

  static const char* value(const ::tm_msgs::Ask_imgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ask_imgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_msgs::Ask_imgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_msgs::Ask_imgResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MSGS_MESSAGE_ASK_IMGRESPONSE_H
