// Generated by gencpp from file tm_msgs/Ask_img_ADRequest.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ASK_IMG_ADREQUEST_H
#define TM_MSGS_MESSAGE_ASK_IMG_ADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tm_msgs
{
template <class ContainerAllocator>
struct Ask_img_ADRequest_
{
  typedef Ask_img_ADRequest_<ContainerAllocator> Type;

  Ask_img_ADRequest_()
    : file_path()  {
    }
  Ask_img_ADRequest_(const ContainerAllocator& _alloc)
    : file_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_path_type;
  _file_path_type file_path;





  typedef boost::shared_ptr< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Ask_img_ADRequest_

typedef ::tm_msgs::Ask_img_ADRequest_<std::allocator<void> > Ask_img_ADRequest;

typedef boost::shared_ptr< ::tm_msgs::Ask_img_ADRequest > Ask_img_ADRequestPtr;
typedef boost::shared_ptr< ::tm_msgs::Ask_img_ADRequest const> Ask_img_ADRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator2> & rhs)
{
  return lhs.file_path == rhs.file_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1f82596372c52a517e1fe32d1e998e8";
  }

  static const char* value(const ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1f82596372c52a5ULL;
  static const uint64_t static_value2 = 0x17e1fe32d1e998e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_msgs/Ask_img_ADRequest";
  }

  static const char* value(const ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_path\n"
;
  }

  static const char* value(const ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ask_img_ADRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_msgs::Ask_img_ADRequest_<ContainerAllocator>& v)
  {
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MSGS_MESSAGE_ASK_IMG_ADREQUEST_H
