// Generated by gencpp from file tm_msgs/Ask_img.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ASK_IMG_H
#define TM_MSGS_MESSAGE_ASK_IMG_H

#include <ros/service_traits.h>


#include <tm_msgs/Ask_imgRequest.h>
#include <tm_msgs/Ask_imgResponse.h>


namespace tm_msgs
{

struct Ask_img
{

typedef Ask_imgRequest Request;
typedef Ask_imgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Ask_img
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::Ask_img > {
  static const char* value()
  {
    return "dc18f33ad8fd47637626ae0ea2c4eb17";
  }

  static const char* value(const ::tm_msgs::Ask_img&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::Ask_img > {
  static const char* value()
  {
    return "tm_msgs/Ask_img";
  }

  static const char* value(const ::tm_msgs::Ask_img&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::Ask_imgRequest> should match
// service_traits::MD5Sum< ::tm_msgs::Ask_img >
template<>
struct MD5Sum< ::tm_msgs::Ask_imgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::Ask_img >::value();
  }
  static const char* value(const ::tm_msgs::Ask_imgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::Ask_imgRequest> should match
// service_traits::DataType< ::tm_msgs::Ask_img >
template<>
struct DataType< ::tm_msgs::Ask_imgRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::Ask_img >::value();
  }
  static const char* value(const ::tm_msgs::Ask_imgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::Ask_imgResponse> should match
// service_traits::MD5Sum< ::tm_msgs::Ask_img >
template<>
struct MD5Sum< ::tm_msgs::Ask_imgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::Ask_img >::value();
  }
  static const char* value(const ::tm_msgs::Ask_imgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::Ask_imgResponse> should match
// service_traits::DataType< ::tm_msgs::Ask_img >
template<>
struct DataType< ::tm_msgs::Ask_imgResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::Ask_img >::value();
  }
  static const char* value(const ::tm_msgs::Ask_imgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_ASK_IMG_H
