// Generated by gencpp from file tm_msgs/Ask_img_ADResponse.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ASK_IMG_ADRESPONSE_H
#define TM_MSGS_MESSAGE_ASK_IMG_ADRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tm_msgs
{
template <class ContainerAllocator>
struct Ask_img_ADResponse_
{
  typedef Ask_img_ADResponse_<ContainerAllocator> Type;

  Ask_img_ADResponse_()
    : anomaly_score()  {
    }
  Ask_img_ADResponse_(const ContainerAllocator& _alloc)
    : anomaly_score(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _anomaly_score_type;
  _anomaly_score_type anomaly_score;





  typedef boost::shared_ptr< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Ask_img_ADResponse_

typedef ::tm_msgs::Ask_img_ADResponse_<std::allocator<void> > Ask_img_ADResponse;

typedef boost::shared_ptr< ::tm_msgs::Ask_img_ADResponse > Ask_img_ADResponsePtr;
typedef boost::shared_ptr< ::tm_msgs::Ask_img_ADResponse const> Ask_img_ADResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator1> & lhs, const ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator2> & rhs)
{
  return lhs.anomaly_score == rhs.anomaly_score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator1> & lhs, const ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96f23771245c7ee86e43cfe9e20d6900";
  }

  static const char* value(const ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96f23771245c7ee8ULL;
  static const uint64_t static_value2 = 0x6e43cfe9e20d6900ULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_msgs/Ask_img_ADResponse";
  }

  static const char* value(const ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] anomaly_score \n"
"\n"
;
  }

  static const char* value(const ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.anomaly_score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ask_img_ADResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_msgs::Ask_img_ADResponse_<ContainerAllocator>& v)
  {
    s << indent << "anomaly_score[]" << std::endl;
    for (size_t i = 0; i < v.anomaly_score.size(); ++i)
    {
      s << indent << "  anomaly_score[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.anomaly_score[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MSGS_MESSAGE_ASK_IMG_ADRESPONSE_H
