// Generated by gencpp from file tm_msgs/Ask_imgRequest.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ASK_IMGREQUEST_H
#define TM_MSGS_MESSAGE_ASK_IMGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tm_msgs
{
template <class ContainerAllocator>
struct Ask_imgRequest_
{
  typedef Ask_imgRequest_<ContainerAllocator> Type;

  Ask_imgRequest_()
    : file_name()  {
    }
  Ask_imgRequest_(const ContainerAllocator& _alloc)
    : file_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_name_type;
  _file_name_type file_name;





  typedef boost::shared_ptr< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Ask_imgRequest_

typedef ::tm_msgs::Ask_imgRequest_<std::allocator<void> > Ask_imgRequest;

typedef boost::shared_ptr< ::tm_msgs::Ask_imgRequest > Ask_imgRequestPtr;
typedef boost::shared_ptr< ::tm_msgs::Ask_imgRequest const> Ask_imgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_msgs::Ask_imgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tm_msgs::Ask_imgRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::Ask_imgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.file_name == rhs.file_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tm_msgs::Ask_imgRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::Ask_imgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2415261c9605b9f38867ffbbe495fc04";
  }

  static const char* value(const ::tm_msgs::Ask_imgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2415261c9605b9f3ULL;
  static const uint64_t static_value2 = 0x8867ffbbe495fc04ULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_msgs/Ask_imgRequest";
  }

  static const char* value(const ::tm_msgs::Ask_imgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_name\n"
;
  }

  static const char* value(const ::tm_msgs::Ask_imgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ask_imgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_msgs::Ask_imgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_msgs::Ask_imgRequest_<ContainerAllocator>& v)
  {
    s << indent << "file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MSGS_MESSAGE_ASK_IMGREQUEST_H
