// Generated by gencpp from file tm_msgs/defect_detect.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_DEFECT_DETECT_H
#define TM_MSGS_MESSAGE_DEFECT_DETECT_H

#include <ros/service_traits.h>


#include <tm_msgs/defect_detectRequest.h>
#include <tm_msgs/defect_detectResponse.h>


namespace tm_msgs
{

struct defect_detect
{

typedef defect_detectRequest Request;
typedef defect_detectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct defect_detect
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::defect_detect > {
  static const char* value()
  {
    return "bcee4f588ea52289bf77bc6d6629f851";
  }

  static const char* value(const ::tm_msgs::defect_detect&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::defect_detect > {
  static const char* value()
  {
    return "tm_msgs/defect_detect";
  }

  static const char* value(const ::tm_msgs::defect_detect&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::defect_detectRequest> should match
// service_traits::MD5Sum< ::tm_msgs::defect_detect >
template<>
struct MD5Sum< ::tm_msgs::defect_detectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::defect_detect >::value();
  }
  static const char* value(const ::tm_msgs::defect_detectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::defect_detectRequest> should match
// service_traits::DataType< ::tm_msgs::defect_detect >
template<>
struct DataType< ::tm_msgs::defect_detectRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::defect_detect >::value();
  }
  static const char* value(const ::tm_msgs::defect_detectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::defect_detectResponse> should match
// service_traits::MD5Sum< ::tm_msgs::defect_detect >
template<>
struct MD5Sum< ::tm_msgs::defect_detectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::defect_detect >::value();
  }
  static const char* value(const ::tm_msgs::defect_detectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::defect_detectResponse> should match
// service_traits::DataType< ::tm_msgs::defect_detect >
template<>
struct DataType< ::tm_msgs::defect_detectResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::defect_detect >::value();
  }
  static const char* value(const ::tm_msgs::defect_detectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_DEFECT_DETECT_H
