// Generated by gencpp from file tm_msgs/robot_state.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ROBOT_STATE_H
#define TM_MSGS_MESSAGE_ROBOT_STATE_H

#include <ros/service_traits.h>


#include <tm_msgs/robot_stateRequest.h>
#include <tm_msgs/robot_stateResponse.h>


namespace tm_msgs
{

struct robot_state
{

typedef robot_stateRequest Request;
typedef robot_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_state
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::robot_state > {
  static const char* value()
  {
    return "8179a08027057ba6ad3ae82542746bab";
  }

  static const char* value(const ::tm_msgs::robot_state&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::robot_state > {
  static const char* value()
  {
    return "tm_msgs/robot_state";
  }

  static const char* value(const ::tm_msgs::robot_state&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::robot_stateRequest> should match
// service_traits::MD5Sum< ::tm_msgs::robot_state >
template<>
struct MD5Sum< ::tm_msgs::robot_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::robot_state >::value();
  }
  static const char* value(const ::tm_msgs::robot_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::robot_stateRequest> should match
// service_traits::DataType< ::tm_msgs::robot_state >
template<>
struct DataType< ::tm_msgs::robot_stateRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::robot_state >::value();
  }
  static const char* value(const ::tm_msgs::robot_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::robot_stateResponse> should match
// service_traits::MD5Sum< ::tm_msgs::robot_state >
template<>
struct MD5Sum< ::tm_msgs::robot_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::robot_state >::value();
  }
  static const char* value(const ::tm_msgs::robot_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::robot_stateResponse> should match
// service_traits::DataType< ::tm_msgs::robot_state >
template<>
struct DataType< ::tm_msgs::robot_stateResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::robot_state >::value();
  }
  static const char* value(const ::tm_msgs::robot_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_ROBOT_STATE_H
